### ISSUE TITLE
Adding stop words doesn't work

### ISSUE THREAD

**Issue by PimHuijnen** [UUDigitalHumanitieslab/texcavator#106]
Am I doing something wrong, or is it impossible to add any more words to the stop word list? Clicking on words in the word cloud doesn't do anything.

**Comment by mhkuu** [comment]
I will do a hotfix on production in a moment.

**Comment by mhkuu** [comment]
I just did a hotfix on production and created a new release tag. Good find and thanks for reporting!

**Comment by PimHuijnen** [comment]
Works like a charm! Many thanks!
