### ISSUE TITLE
Visualize metadata of results

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#11]
Add an overview of distribution, article type and newspaper (categorized as in #10?). Bar charts are probably the best option here.

**Comment by mhkuu** [comment]
See http://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html for a possible solution. For visualization we can use Jannekes prototype.

**Comment by melvinwevers** [comment]
What do you think about: https://www.elastic.co/products/kibana

I'm now sure if it's easily integrated into Texcavator, but I think the type of visualizations we are looking for are available out-of-the-box in Kibana.

**Comment by melvinwevers** [comment]
@mhkuu could you post Janneke's prototype?

**Comment by mhkuu** [comment]
I'll look into Kibana but it probably won't be a walk in the park to integrate that into Texcavator :-) 

This is from Janneke's prototype, visualizations made with [nvd3](http://nvd3.org/). ![texcavator_results](https://cloud.githubusercontent.com/assets/7521233/7490420/a3f63836-f3e0-11e4-959f-3c3fde46bd8d.png)

**Comment by mhkuu** [comment]
Metadata graph will be loaded when a cloud for a saved query is generated. 

For the newspapers overview this will require a re-mapping of the ElasticSearch index.
