### ISSUE TITLE
Scans from 1945 onwards no longer available

### ISSUE THREAD

**Issue by JosedeKruif** [UUDigitalHumanitieslab/texcavator#114]
Query: "Mainzer Beobachter". 74 hits. Ask for OCR in first 15 hits of list and only text is shown, not the OCR.

**Comment by mhkuu** [comment]
Apparently the metadata (which includes the location of the scan on the imaging server) is not being retrieved for those records. We'll have to investigate this further.

**Comment by mhkuu** [comment]
Just found out requesting the KB scans from after 1945 requires an API key. So we'll have to implement that or change the fetching process.

**Comment by mhkuu** [comment]
Currently resolved by using an API key to retrieve the article pages and areas from the API. I think it would be a good idea to put these into the elasticsearch index instead.

**Comment by mhkuu** [comment]
Opened #126 for the comment above, this one is resolved.
