### ISSUE TITLE
No default for normalization word clouds

### ISSUE THREAD

**Issue by melvinwevers** [UUDigitalHumanitieslab/texcavator#122]
Since there is no default for normalizing word clouds, generating of a normalized word cloud yields no output. Perhaps use the middle setting as default?

**Comment by mhkuu** [comment]
Strange, it works for me on Chrome. Safari issue maybe?

**Comment by jgonggrijp** [comment]
I am unable to reproduce this issue in Safari. Could you describe the steps that you have taken?

**Comment by mhkuu** [comment]
I wasn't unable to reproduce this at first either, but now it does happen with me on Chrome as well (sometimes). Might be a Heisenbug... I assume that there's some rogue asynchronous JavaScript when the application is loaded.

**Comment by mhkuu** [comment]
Found the problem; this only happens if you have not yet opened the config window when you ask for a word cloud. After initial opening of the config window everything works as desired. I'll move the opening of the config window to startup of the application.
