### ISSUE TITLE
Make timelines clearer

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#13]
- [x] Add y-axis to the graph (http://bl.ocks.org/stepheneb/1182434 maybe?)
- [x] at the end of the timeline there seems to be a bar that doesn't display anything
- [x] when filtered on time, wrong dates are shown in the title 
- [x] the word cloud is sometimes rendered on top of the graph instead of below it
- [x] from the error log: Internal Server Error: /query/timeline/1390/year

**Comment by melvinwevers** [comment]
@mhkuu there is a bug with the timeline in Safari. 
Also what does the burst mean? Can you tell us how Texcavator calculates the bursts?

**Comment by mhkuu** [comment]
@melvinwevers Yes that's issue #29 :+1: 
The bursts are calculated using [Kleinberg's burst detection algorithm](http://www.cs.cornell.edu/home/kleinber/bhs.pdf). If I have some time available I'll try and come up with a short description :-)

**Comment by melvinwevers** [comment]
Fail.

**Comment by melvinwevers** [comment]
btw, the reference to this paper will suffice. We can refer to this as well. Thanks.

**Comment by mhkuu** [comment]
Other issues: 
- at the end of the timeline there seems to be a bar that doesn't display anything
- when filtered on time, wrong dates are shown in the title 
- the word cloud is sometimes rendered on top of the graph instead of below it
