### ISSUE TITLE
Remove labels from metadata graphs

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#131]

**Comment by jgonggrijp** [comment]
Why?

**Comment by JosedeKruif** [comment]
Because now we have double labels in one graph.
Greetings from Texel :D

José de Kruif

Op 1 aug. 2016 om 10:07 heeft Julian Gonggrijp <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Why?
