### ISSUE TITLE
increase size query text box

### ISSUE THREAD

**Issue by melvinwevers** [UUDigitalHumanitieslab/texcavator#139]
The box for the query is rather small. More than often you have to scroll through your query. Since there is enough space left, I would propose to increase the size of the search box.

**Comment by jgonggrijp** [comment]
How much space is left, depends on the width of your browser window. Maybe we can let the search box grow with the available space.

In any case, the edit button is there to give you more space. :-)

**Comment by JosedeKruif** [comment]
Also very nice: when one uses the edit button, the box growths with your query. Neat.

**Comment by melvinwevers** [comment]
I think most people still have a lot of space left. Also generally, query windows are much larger, in the past it also used to be bigger. 

The edit button is not convenient and unintuitive, because it requires an additional action and the resizing of the query is rather clunky imho. Why give the impression that it is restricted, only to increase in size after typing? Perhaps it is an idea to increase the default size, for instance to fill up the size of the pop up. 

Anyhow, from a UI perspective, it's always best to come up with an easy solution that does not require to many additional clicks and actions. In this application querying is one of the most common actions, so it makes sense to increase the size and make it responsive to browser width.

**Comment by JosedeKruif** [comment]
Yes, the edit button means one extra click for the user. On the other hand, this is not a bug and since there is no funding at this moment, there is no more time for enhancements. I will mention in the user manual that the edit box expands when using a lengthy query. When additional funding is found, this might be one of the enhancements in the user interface to think of.
