### ISSUE TITLE
Change font for newspaper titles in metadata graph (histogram at the bottom)

### ISSUE THREAD

**Issue by JosedeKruif** [UUDigitalHumanitieslab/texcavator#142]
Can not read some newspapertitles.

![bugmetadatatexontwikkelversieinfirefox](https://cloud.githubusercontent.com/assets/7069444/18263626/da0dcc7a-740b-11e6-8e29-9e8c3b92aa1e.jpg)

**Comment by melvinwevers** [comment]
Bij de meeste kranten lost het probleem zich op als je de string afkapt na de dubbele punt.
