### ISSUE TITLE
Corpora in texcavator version

### ISSUE THREAD

**Issue by melvinwevers** [UUDigitalHumanitieslab/texcavator#143]
Hi,

I'm now using the HUM hosted version of Texcavator, but I seem to be finding different results than with the surfsara version, for instance total number of Telegraafs in one year. I cannot check with the Surfsara version because it's still offline, but do you know whether this is a different data set.

**Comment by JosedeKruif** [comment]
It is all the same dataset as far as I know.

**Comment by mhkuu** [comment]
Hi @melvinwevers, the dataset is indeed exactly the same between the two servers. Only difference is that texcavator.hum.uu.nl runs the latest develop source code revision, and texcavator.surfsaralabs.nl runs the latest master revision. Currently they should run on the revision though. What's the query you are running?

**Comment by melvinwevers** [comment]
Hi @mhkuu, yeah they are now the same. Yesterday they differed. Maybe it was that bug that occurred in the past when you had to click the search button twice. Perhaps a caching issue. Well, it works now. Thanks!

**Comment by mhkuu** [comment]
Thanks for reporting!
