### ISSUE TITLE
Hoovering results in strange text display

### ISSUE THREAD

**Issue by JosedeKruif** [UUDigitalHumanitieslab/texcavator#150]
When hoovering left window with list of articles, right window starts behaving funny. I add a screenshot to illustrate what happens. Query: archivaris in national and regional newspapers 344 hits.
![hooverbugtexcavator](https://cloud.githubusercontent.com/assets/7069444/19237987/b8c04638-8eff-11e6-8897-4259eb0b7b86.jpg)

**Comment by jgonggrijp** [comment]
I'm unable to reproduce this in Safari, Firefox and Chrome, both in the production environment and the development environment. I also get much more results when I try the query you described. Could you provide more details on how to get into this dire situation? In particular:

- What browser are you using?
- Full details of your configuration (filter settings)?
- Time range?
- Full sequence of buttons and other widgets that you clicked on, between pressing enter to launch the search and hovering an article link to get the above hyperlink?
- Does the hover bug always appear, or only when particular search hits are open?
- Can you trigger the bug by hovering any search hit, or does it only work with some?

**Comment by mhkuu** [comment]
I suspect it's a particular search result where this happens, which has a text content that doesn't like being split on spaces: https://github.com/UUDigitalHumanitieslab/texcavator/blob/e46f92a6c9c28345b746aacecf79358ca218f014/texcavator/static/js/uva/ocr.js#L24. Could be the ">" character that interferes.

**Comment by JosedeKruif** [comment]
Browser: Firefox version 49.0.1
Filter in Texcavator (at surfsaralabs.nl): regular articles and kb illustration text and national newspapers only
Search for: archivaris
Save query
Click on saved query
Ask for timeline
Click on timeline burst 1928-1929
Choose hit nr 5 in article list titled "archiefwezen"
Hoover over image of article 
Voila (text of paragraph in the middle now appears in funny format at the bottom of the screen)
Sorry for the hassle, should have mentioned these steps in the first place.
