### ISSUE TITLE
Multiple date selections

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#22]
Allow a user to select two (or more) periods of dates, e.g. 01-01-1900 to01-01-1914 and 01-01-1965 to 01-01-1970.

**Comment by lisannewalma** [comment]
When I use multiple date selection, and subsequently apply the query, the timeline generated also shows the article distribution for dates not selected (e.g. below: I wanted articles between 1850 - 1900 and 1920 - 1990, but the timeline shows articles from 1850 - 1990)
![untitled](https://cloud.githubusercontent.com/assets/12531136/9958808/c1d26180-5e0d-11e5-8a24-6380da7689b9.png)
