### ISSUE TITLE
Default stopword list

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#28]
- [x] Allow a set of stopwords that is available by default for all users and queries. 
  - This required a small database migration, this has to be executed on the server. 
- [x] Allow for easy modification of this set of stop words. 
  - This can be done via the admin section by "staff" users. Might require some configuration on the server. 
- [x] Allow users to download the set of stop words (including their own additions). 
- [x] Create a management command to add stopwords from a .txt-file (for initial setup)
  - Command: `python manage.py add_stopwords stopwords/nl.txt`
- [x] Create an initial set of stopwords
  - See [here]( https://github.com/UUDigitalHumanitieslab/texcavator/blob/develop/query/management/commands/stopwords/nl.txt).

**Comment by melvinwevers** [comment]
Here you can find my list of stopwords: https://github.com/melvinwevers/stopwordlist/blob/master/nl.txt

**Comment by mhkuu** [comment]
@melvinwevers Thanks, I'll merge this file with a stop word list from @JosedeKruif. You probably want to go over your list though, a word like `sigaret` seems tailored for your purposes ;)

**Comment by melvinwevers** [comment]
Haha. For sure. Let me know when you have merged the files, and I'll go over the list.

**Comment by mhkuu** [comment]
@melvinwevers The stop word list has been updated by @JosedeKruif, see [here](https://github.com/UUDigitalHumanitieslab/texcavator/blob/develop/query/management/commands/stopwords/nl.txt) for the current list. You can reopen this issue (or create a pull request) if you want words added/deleted :-).
