### ISSUE TITLE
Timelines do not work in Safari

### ISSUE THREAD

**Issue by melvinwevers** [UUDigitalHumanitieslab/texcavator#29]
See screenshot:

![screenshot 2015-04-29 14 18 30](https://cloud.githubusercontent.com/assets/6586849/7390657/a2aea0dc-ee7a-11e4-94d6-f99b5b188eed.png)

priority not very high

**Comment by melvinwevers** [comment]
This issue can be closed.

**Comment by mhkuu** [comment]
Well I haven't solved this during #13 so I'll keep this on the backlog as a minor issue.

**Comment by mhkuu** [comment]
This seems to have been fixed during #47, in which I changed the rendering of the bars of the timeline graph.
