### ISSUE TITLE
Add date modified column on Query

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#33]
A date_modified column might be helpful on a Query, also when exporting the Query; now the date_created is shown, but this might well differ from the date the query was last changed.

**Comment by melvinwevers** [comment]
Low priority

**Comment by mhkuu** [comment]
Actually the date_created is updated on modification. So this can be closed.

**Comment by mhkuu** [comment]
Never mind, I'll correct the date_created and add a new field date_modified with the correct settings.
