### ISSUE TITLE
Texcavator results don't match up with Delpher

### ISSUE THREAD

**Issue by melvinwevers** [UUDigitalHumanitieslab/texcavator#35]
Als je bij een OR query twee keer hetzelfde woord invult dus bv. "aap" OR "aap" dan krijg je twee zoveel resultaten als wanneer je alleen aap invult. Dit lijkt me een "bug" en geen "feature."

**Comment by melvinwevers** [comment]
Daarbij aansluitend. 

De query "multi-national" OR multinational" levert in delpher 8618 artikelen op (filter artikelen tussen 45 en 84) en in texcavator 3982.

Als ik hiervoor een wordcloud genereer staat Amerikaanse hierin met n=1495. Als ik dan op Amerikaanse klik (via html canvas wordcloud) ontstaat de volgende query "multinational" or "multi-national" AND "amerikaanse". Dit geeft maar 46 resultaten (in Delpher 1466). Wanneer ik de syntax verander naar ("multinational" OR "multi-national") AND "amerikaanse" krijg ik 858 resultaten. 

Ergens gaat hier iets grandioos mis.

**Comment by mhkuu** [comment]
Dat eerste (`x OR x`) is erg raar; daar moeten we verder naar kijken. Lokaal kan ik het niet reproduceren maar misschien dat op productie een probleem zit met de duplicatie. 

Het tweede weet ik niet hoe dat zit. Krijg je voor andere queries wel dezelfde resultaten in Texcavator en Delpher? 

Voor wat betreft het derde: `x OR y AND z` is wat anders dan `(x OR y) AND z`; het betekent in Elasticsearch dat je `y` en `z` in je resultaat wilt, en mogelijk `x`. Dat klinkt (ook voor mij) raar. Ze raden aan om +/- te gebruiken in plaats van OR/AND/NOT: https://www.elastic.co/guide/en/elasticsearch/reference/1.x/query-dsl-query-string-query.html#_boolean_operators. Dientengevolge moeten we misschien vanuit de html canvas cloud ook die syntax gebruiken in plaats van ORs en ANDs toe te voegen.

**Comment by melvinwevers** [comment]
De resultaten verschillen soms licht, in dit geval zijn het wel grote verschillen. 

Het is goed om die handleiding er altijd bij te houden, inderdaad. 

Qua cloud hangt het beetje af van welke model we uiteindelijk kiezen. Ik heb het genoemd omdat ik via deze weg achter het verschil in resultaten kwam.

**Comment by melvinwevers** [comment]
Ik blijf het vreemd vinden. Als ik OR zoek volgens de handleiding van Elastic hoef ik niet toe te voegen, twee woorden zijn in principe al OR. 

Als ik zoek op "sigaret*" "cigaret*" krijg ik in Texcavator (regional/national/articles/advertisements) van 1915 tot 1920: 4.352 results

in Delpher met dezelfde query: 12.545
http://www.delpher.nl/nl/kranten/results?query=sigaret*+or+cigaret*&facets%5Bspatial%5D%5B%5D=Landelijk&facets%5Bspatial%5D%5B%5D=Regionaal%7Clokaal&facets%5Btype%5D%5B%5D=advertentie&page=1&cql%5B%5D=(date+_gte_+%2201-01-1905%22)&cql%5B%5D=(date+_lte_+%2231-12-1919%22)&coll=ddd

**Comment by JosedeKruif** [comment]
Ja wat ik vreemd vind, is dat je het vreemd vind dat je erg verschillende resultaten krijgt als je heel verschillende queries invoert. Ten eerste zeg je: "Als ik zoek op "sigaret" "cigaret" krijg ik in Texcavator (regional/national/articles/advertisements) van 1915 tot 1920: 4.352 results", terwijl je in de Delpher query daaronder hebt gezocht op 01-01-1905 - 31-12-1919. En dan heb je in Delpher wildcards gebruikt (twee keer *) en in Texcavator niet. Als ik in Texcavator zoek zonder wildcards krijg ik inderdaad ook maar weinig resultaten. Zoek ik echter mét wildcards dan krijg ik veel meer. 
Trek eerst de queries gelijk zowel qua vorm als qua periode. En dan zul je overigens nog steeds verschillen krijgen. Het is bekend dat de ESdatabase moet worden vernieuwd . Je kunt dus blijven zoeken naar verschillen en die zullen ook optreden. Maar misschien is het nuttig te wachten met dit soort meldingen tot je 1. Zeker weet dat het om dezelfde query gaat 2. De ES database beter vergelijkbaar is met de huidige van Delpher.

**Comment by melvinwevers** [comment]
Ik was inderdaad vergeten om te vermelden dat ik het met en zonder wildcards heb geprobeerd. En ik heb meerdere tijdsperiode geprobeerd.

Los daarvan zijn de verschillende erg groot, en anders dan voorheen. Ik had namelijk de resultaten geëxporteerd alsook de query. Natuurlijk weet ik dat ik dezelfde queries moet gebruiken, en zal ik secuurder zijn in het noteren

We kunnen dit probleem wel voor ons uit schuiven, maar het punt blijft staan dat er grote verschillen zijn, als je wel dezelfde periode en query invoert, die niet kan verklaren en dus hier aan geef. Dus laten we gewoon eens constructief hiernaar kijken ipv het over onduidelijkheden in mijn formulering te hebben. Ik ben ook niet de enige die dit vindt trouwens. Misschien kunnen we hier volgende week een moment voor vinden.

**Comment by JosedeKruif** [comment]
Toch zou ik graag een voorbeeld krijgen van eenzelfde query en van de verschillen in resultaat die dan optreden bij jou of bij jullie. Wij willen het probleem zeker niet voor ons uit schuiven, integendeel, maar zijn druk in overleg over het updaten en opnieuw indexeren van de ES database.

**Comment by melvinwevers** [comment]
OK. Ga ik aanleveren

**Comment by melvinwevers** [comment]
Bij deze:

**Tex**: "sigaret*" "cigaret*" 1905 tot 1920 (article + ad) = 4352
**Tex**: "sigaret*" OR "cigaret*" 1905 tot 1920 (article + ad) = 4352
**Delpher**: sigaret*" OR "cigaret*" 1905 tot 1920 (article + ad) = 25.506

_Een erg groot verschil._

**Tex**: "sigaret*" AND "cigaret*" 1905 tot 1920 (article + ad) = 14
**Tex**: +"sigaret*" +"cigaret*" 1905 tot 1920 (article + ad) = 14
**Delpher**: sigaret*" AND "cigaret*" 1905 tot 1920 (article + ad) = 233

_Hier zien we ook een verschil._ 

Als ik alleen zoek op "Amerika"
**Tex** "Amerika" 1900 tot 1950 (article + ad) = 1.071.762
**Delpher** = 1.108.656

_Dat ligt dan weer heel dicht bij elkaar. Ik denk dat er iets mis gaat bij Delpher bij OR queries, maar ik kan dit moeilijk controleren._

Aanvullend, wordt bij het invullen van een hetzelfde woord in een OR query (AAP or AAP) niet meer een verdubbeling voor. Dus dat is mooi.

**Comment by brammellink** [comment]
Ik ondervind hetzelfde probleem als Melvin, ditmaal bij het invoeren van een grotere, gecombineerde AND/or-query.

<b>Query</b> ("planning" OR "ordening" OR "socialisatie" OR "nationalisatie" OR "welvaartsstaat" OR "verzorgingsstaat") AND ("welvaart" OR "econom*" OR "vrijh*" OR "conjunct*")
<b> periode </b> 05-05-1945 t/m 31-12-1963

<b> Texcavator: </b> 1375 records
<b> Delpher: </b> 3220 records

**Comment by JosedeKruif** [comment]
Invoerbeperking wordt eerdaags geïmplementeerd zodat AND of OR niet meer mogelijk zijn. Wat betreft de update van de set: KB verwacht over ongeveer twee maanden een nieuwe set te publiceren. We zullen dan in overleg met Jeroen Schot proberen die te harvesten.
