### ISSUE TITLE
Add prev/next buttons below search results

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#37]
See title.

**Comment by melvinwevers** [comment]
There is a bug re: the next/prev button.

I have used a query with a large list of results "buffalo" between 1918 and 1939. I then pushed next several times. (6 page, I guess). Then I changed the periodization to 1937-1939. And pushed search again. This generated a smaller list of results, but I was still on the 6th page, so I had to push back several times.

**Comment by mhkuu** [comment]
Good find! This should be fixed on the development server, in commit 2f7a15de5d78e6f1e2ed927694b61273f49d1e33.
