### ISSUE TITLE
Editing queries via menu is broken

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#39]
See title, refers to non-existing API endpoint. 

There is a simple workaround however: open the query, change the search term, and then re-save. I think it's best to only allow that option and delete the other one.

**Comment by melvinwevers** [comment]
Remove this feature.
However, when you open query, edit the query, you cannot overwrite it. This would be useful.

**Comment by jgonggrijp** [comment]
Overwriting queries is possible, as far as I can tell.

 1. Re-search or apply saved query.
 2. Modify the query.
 3. Open "Saved queries" panel.
 4. Optionally, enter a new query name.
 5. Click the diskette icon "Modify" next to the query that you wish to overwrite.

**Comment by melvinwevers** [comment]
It might be better if this function could be moved to the save button with a dialogue asking whether you want to override the query.
