### ISSUE TITLE
Download newspaper overview

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#43]
Add a button to download the overview of newspapers with the pillarization.

**Comment by melvinwevers** [comment]
Where can I find this button?

**Comment by mhkuu** [comment]
It's a bit hidden and not really a button, sorry! :-) Click Config -> Search -> scroll down, "download distribution as .csv". I'm open to better suggestions.

**Comment by melvinwevers** [comment]
Perhaps, a button on the page with the distributions? It would be neat to be able to also download the graphs. Let's discuss this tomorrow.
