### ISSUE TITLE
Word cloud generation hiccups 

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#5]
The word cloud generation sometimes hiccups. According to @jvdzwaan this might be due to the communication between Django/Redis/Celery. Maybe replace Redis with RabbitMQ.

**Comment by jvdzwaan** [comment]
Another theory we developed about this problem that it has to do with cookies and not properly logging in/out. I think the Dojo front end does log in properly (meaning: using django standard functionality), but doesn't log out properly (it only resets some javascript variables, but sends nothing to Django). So, it also might be a session problem.

**Comment by mhkuu** [comment]
Closing this for now; fixed this in timelines. Let's reopen this if we have a something reproducable. Logging in/out via Django is covered in #15.

**Comment by melvinwevers** [comment]
The generation of word clouds does not seem to work. I have deleted my cookies and tried both Safari and Chrome.

**Comment by mhkuu** [comment]
I restarted the server; word cloud generation seems to work again. I can't get to the server logs right now for a postmortem but I'll try to get a hold of them when our SurfSara contact is back from his holiday.


Martijn van der Klis | M.H.vanderKlis@uu.nl<mailto:M.H.vanderKlis@uu.nl> | Ontwikkelaar UiL OTS labs / Digital Humanities | Fac. Geesteswetenschappen | Universiteit Utrecht

UiL OTS: http://uilots-labs.wp.hum.uu.nl/ | T. (030) 253 6248 | Janskerkhof 13/A, 3512 BL Utrecht | kamer 0.09 | di / vr

DH: http://digitalhumanities.wp.hum.uu.nl/ | T. (06) 49836692  | Muntstraat 2a, 3512 EV Utrecht | kamer T2.13A (KNG20-kant) | wo / do

________________________________
Van: Melvin Wevers [notifications@github.com]
Verzonden: woensdag 10 juni 2015 14:22
Aan: UUDigitalHumanitieslab/texcavator
CC: Klis, M.H. van der (Martijn)
Onderwerp: Re: [texcavator] Word cloud generation hiccups (#5)


The generation of word clouds does not seem to work. I have deleted my cookies and tried both Safari and Chrome.

**Comment by melvinwevers** [comment]
Thanks.

**Comment by jesperverhoef** [comment]
I encounter the same problem Melvin addressed yesterday: The generation of word clouds does not work. I have deleted my cookies and tried both Safari and Chrome.

**Comment by mhkuu** [comment]
I restarted the server again. We'll have to look into this with our SurfSara contact next week.


Martijn van der Klis | M.H.vanderKlis@uu.nl<mailto:M.H.vanderKlis@uu.nl> | Ontwikkelaar UiL OTS labs / Digital Humanities | Fac. Geesteswetenschappen | Universiteit Utrecht

UiL OTS: http://uilots-labs.wp.hum.uu.nl/ | T. (030) 253 6248 | Janskerkhof 13/A, 3512 BL Utrecht | kamer 0.09 | di / vr

DH: http://digitalhumanities.wp.hum.uu.nl/ | T. (06) 49836692  | Muntstraat 2a, 3512 EV Utrecht | kamer T2.13A (KNG20-kant) | wo / do

________________________________
Van: jesperverhoef [notifications@github.com]
Verzonden: donderdag 11 juni 2015 10:29
Aan: UUDigitalHumanitieslab/texcavator
CC: Klis, M.H. van der (Martijn)
Onderwerp: Re: [texcavator] Word cloud generation hiccups (#5)


I encounter the same problem Melvin addressed yesterday: The generation of word clouds does not work. I have deleted my cookies and tried both Safari and Chrome.

**Comment by PimHuijnen** [comment]
Texcavator, again, seems down. The generation of word clouds and timelines does not work. I, also,  have deleted my cookies and tried both Safari and Chrome.

**Comment by JosedeKruif** [comment]
I have informed Martijn yesterday that Texcavator is down. I will try to contact Jeroen today, since there has been a transfer of servers at SurfSara.  This seems to cause multiple problems, it might take several days before Texcavator is up and running again.
