### ISSUE TITLE
Exporting special characters

### ISSUE THREAD

**Issue by jesperverhoef** [UUDigitalHumanitieslab/texcavator#56]
Importing a tab separated file from Texcavator into OpenRefine – in order to clean the results (e.g. delete double issues of theTelegraaf, get rid of metadata I won’t need in tools such as AntConc) – results in the following issue: OpenRefine seems unable to read certain special characters. For instance, before  „ (lower quotation mark) it places â€ž, and before every French quotation mark (« - resulting from OCR errors) it inserts Â. In the settings, OpenRefine correctly recognizes the code of the file to be UTF-8. 
	Melvin and I were wondering, could this issue be caused by Texcavator not encoding the output, in particular the special characters, strictly?

**Comment by mhkuu** [comment]
Priority: 3.

**Comment by mhkuu** [comment]
Can you add clearer steps to reproduce this issue? E.g. a query and a document number with which this happens? The [export code](https://github.com/UUDigitalHumanitieslab/texcavator/blob/e9155168ae9bc59dc94967138bc5aa8c5f359cca/query/tasks.py#L388) says everything is encoded into utf-8.

**Comment by jesperverhoef** [comment]
I used, e.g., this query in Texcavator

((quiz OR quiz* OR kwis OR kwis*) AND (tv OR t.v. OR televisi* OR tv* OR t.v.*)) -kwispedoor -kwispel -kwistig -kwispel* 

I was only interested in regional and national newspaper articles (so no advertisements etc.). The first result is 'NCRV-50-quiz'. The OCR in Tex looks like this: 

De „Kwis-50" begint op 31 augustus

OpenRefine renders it as:

De â€žKwis-50" begint op 31 augustus

**Comment by mhkuu** [comment]
@jesperverhoef, thanks for the steps to reproduce. I can indeed reproduce the error. OpenRefine (I use version v2.5, r2407) however does render the text as **„Kwis-50"** when you explicitly select "UTF-8" as the character encoding for the file. 

In your opening comment you say that OpenRefine *"recognizes the code of the file to be UTF-8"*; I don't see that happening in my version of OpenRefine, I have to set that explicitly in the preview phase after I've uploaded the file, so maybe you're using another version?

**Comment by mhkuu** [comment]
Considering this solved.
