### ISSUE TITLE
Remove duplicate newspapers from index

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#59]
Priority: 2. Maybe related to #35. We'll receive input from the Translantis team on this.

**Comment by JosedeKruif** [comment]
Van Steven Claeyssens kreeg ik nog de volgende informatie: "de achtcijferige identifiers beginnen bij 00000001 en lopen op. Er is een afzonderlijke serie batches waarvan de identifier begint bij 10000001 en oploopt; dit betreft batches waarvan de microfilms door de KB gescand zijn en de rest van de digitalisering door het digitaliseringsbedrijf CCS is gedaan (stroom microfilm_KB)." Steven had dit al doorgegeven aan Pim Huijnen, maar die heeft het nog niet op het DH Lab laten landen.

**Comment by melvinwevers** [comment]
@mhkuu 

Is er een manier om dit makkelijk eruit te filteren binnen de query? Ik kan wel kranten eruit krijgen, maar hij wil geen wildcards invoeren op de categorie _id zie bijvoorbeeld. 

"coca-cola" -identifier: "ddd:110591427:mpeg21:a0198"

Hiermee krijg ik wel dit ene record eruit, maar ik zou graag het volgende willen:

"coca-cola" -identifier: "ddd:11*" 
Wat is de juiste syntax hiervoor?

**Comment by mhkuu** [comment]
@melvinwevers De juiste syntax hiervoor is `"coca-cola" -identifier:ddd\:11*`. Dus zonder de quotes (die zorgen voor exact matching) en met een escape voor de dubbele punt.

Zie ook https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_field_names en het kopje over wildcards (en ook de waarschuwing dat een wildcard aan het begin van een expressie niet zo'n slim idee is :-)).

**Comment by jgonggrijp** [comment]
Temporary fix: automatically append `-identifier:ddd\:11*` to the end of every query, until the duplicates have been removed. Remove the appendix in a hotfix release when the database is updated.

**Comment by mhkuu** [comment]
This is now a duplicate of #94, closing this one.
