### ISSUE TITLE
Filtering not applied to timelines

### ISSUE THREAD

**Issue by melvinwevers** [UUDigitalHumanitieslab/texcavator#61]
I have made a corpus of advertisements in national and regional newspapers using the following query: "coca-cola" AND (Ameri* OR "Verenigde Staten" OR U.S.A. OR USA) -paper_dc_title: "De Surinamer" 

This query yields 252 results. 

When I generate a timeline, it seems as if this is based no longer on only advertisements but on all article types. See screenshots. I've been using these time lines a lot lately, and I've based some analyses on them (also in articles I would like to publish). It would be a shame if they would not correspond to my query. 

<img width="1289" alt="screenshot 2015-09-02 16 02 22" src="https://cloud.githubusercontent.com/assets/6586849/9633233/0e98c6a0-518c-11e5-9650-25b9795ef9a5.png">

**Comment by melvinwevers** [comment]
<img width="1292" alt="screenshot 2015-09-02 16 05 02" src="https://cloud.githubusercontent.com/assets/6586849/9633299/6463a46a-518c-11e5-989f-092f1388a19d.png">

**Comment by melvinwevers** [comment]
When I do the same query on all article types, it yields the same time line. So the filtering is not being applied to the time lines.

**Comment by mhkuu** [comment]
Correct, I noticed that yesterday as well. However since no-one reported this issue before I was really unsure whether this may have once been a feature instead. I (probably) fixed this in f74c9ef5dea8279c83fd78e4c2a63c8a5436a84d though.

**Comment by melvinwevers** [comment]
Great!

**Comment by melvinwevers** [comment]
Has this change been committed to the develop environment? 
Because the filtering is not being applied in this version either.

**Comment by mhkuu** [comment]
Hi @melvinwevers! This morning I moved the development environment to a new server and updated the code as well, it seems to work now (but please do test). See BaseCamp for more details.

**Comment by melvinwevers** [comment]
Yes! it works on the development environment. Could you include this in the next version on Production?

**Comment by mhkuu** [comment]
Yes, we'll do a deployment of issues in Milestone 4 just after the Texcavator user meeting; if this is a pressing issue I can make a hotfix release.

**Comment by melvinwevers** [comment]
If possible that would be great!

**Comment by melvinwevers** [comment]
When will milestone 4 be deployed?

**Comment by mhkuu** [comment]
I have an appointment for deployment for tomorrow afternoon (15.00) with our SurfSara contact :-)
