### ISSUE TITLE
Change position of export metadata

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#66]
Comment by @melvinwevers on #9: 

*Would it be an idea to add the meta-information at the bottom or in a column instead of a row? 
Many programmes expect the first row to contain row information. I now need to first remove this first row to be able to do anything with the files.*

My suggestion would then be the bottom rows and/or an extra file (could be plain .txt) in the .zip-archive with the metadata.

**Comment by melvinwevers** [comment]
I think bottom rows would be best. Less change of losing files ;)

**Comment by jgonggrijp** [comment]
New plan: add a column for the metadata. Column header is just a name, first "data" cell contains the metadata, remaining cells are empty.

**Comment by mhkuu** [comment]
The first column now is called "metadata". It has one filled cell, which states the metadata of the query in JSON format.
