### ISSUE TITLE
Small improvements to the layout

### ISSUE THREAD

**Issue by jesperverhoef** [UUDigitalHumanitieslab/texcavator#70]
The Config menu could be better organized:
 - [x] Under search: maybe 'pillar' can be placed next to 'distribution', for we think it's when researchers realize that both are possible (without having to scroll down)
 - [x] Under cloud:  does 'Require fresh cloud (ignore browser cache)' work? If not, can be removed
 - [x] regarding stop words, it is unclear to us whether multiple stop word lists are used. If not, the two check boxes should be switches: when the one is turned on, the other should be turned off.
 - [x] If there are two lists, it would be nice to say in brief what the other list / is based on. 
 - [x] Under timeline: can we place a link to the article (which Martijn shared with us) explaining what 'normalize document counts' entails?
 - [x] Under export: It say 'Cloud CSV export options', but actually the standard is TSV. Therefore, it would probably be better to remove CSV and just state: 'Cloud export options'. 
 - [x] Sentiment tab can be removed
 - [x] NER tab can be removed, since there are no options one can switch on and off
 - [x] System tab can be removed for the same reason. 

Plus, not in the Config tab but elsewhere:

 - [x] We think it's better to rename the 'Query' tab 'Export' tab
 - [x] The 'name' button, in my case jesperverhoef (in the upper right corner) could be renamed 'logout', since this is what it offers.

**Comment by jesperverhoef** [comment]
Plus, not in the Config tab but elsewhere:

-We think it's better to rename the 'Query' tab 'Export' tab
-The 'name' button, in my case jesperverhoef (in the upper right corner) could be renamed 'logout', since this is what it offers.

**Comment by jgonggrijp** [comment]
> regarding stop words, it is unclear to us whether multiple stop word lists are used. If not, the two check boxes should be switches: when the one is turned on, the other should be turned off.

I'm a bit confused by this point. I think, if there is no choice with regard to the list being used, that the second checkbox can be dropped entirely. Is that what you mean?

**Comment by melvinwevers** [comment]
@jgonggrijp it is not clear whether there are two lists: one small default list and the list we have once produced. If this is the case a selector would make sense. If not, than the option can be dropped.

**Comment by mhkuu** [comment]
The option actually does something else: it adds the default list of stopwords to your own set of stopwords. So I renamed it to: "Use the default stop word set on top of your own set of stopwords". "Remove stopwords" sets whether you actually want to remove stopwords. I added that if this is unchecked, the other button is unchecked as well.

**Comment by mhkuu** [comment]
I can't find any scientific paper on how the normalization works. In the code it works as follows (I think): 
- for each year, retrieve the absolute frequencies of the search term
- for each year, also retrieve the total frequency. 
  - then, retrieve the maximum of these total frequencies.
  - then, per year, divide the total frequency by this maximum value.
- then, per year, divide the absolute frequency by the normalized frequency. 

[This guy on Stackoverflow](http://stackoverflow.com/questions/13638464/normalizing-by-max-value-or-by-total-value) does something along these lines. 

The code is written by Maria-Hendrike Peetz in 2011. 

I hope this helps.
