### ISSUE TITLE
Normalization timeline does not work

### ISSUE THREAD

**Issue by melvinwevers** [UUDigitalHumanitieslab/texcavator#71]
After checking the normalize checkbox in settings, the same timeline is produced.

**Comment by melvinwevers** [comment]
Last meeting, we discussed applying a different way of calculating normalizations to the time-lines. 
Is this something for the next milestone? (I can't recall)

**Comment by melvinwevers** [comment]
Moreover, it is not clear how to interpret the y-axis for the normalized timeline. These are no longer absolute numbers.

**Comment by mhkuu** [comment]
Moved comment to #86. Locked conversation here.
