### ISSUE TITLE
Efficient saved queries

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#75]
Currently all saved queries are displayed as a list, which is (1) unclear and (2) bad for performance, as for each line the number of results in the index is requested. This seems to sometimes lead to connectivity problems. The number of results could be saved on a query.

**Comment by marijnschraagen** [comment]
possibly relevant: https://www.elastic.co/guide/en/elasticsearch/guide/current/_limiting_memory_usage.html#circuit-breaker
