### ISSUE TITLE
Dash problems

### ISSUE THREAD

**Issue by melvinwevers** [UUDigitalHumanitieslab/texcavator#78]
When I do the search "Coca-Cola" it gives the same amount of results as when I enter "Coca Cola"
Texcavator interprets the - as a space. Is there a way I can circumvent this?

**Comment by JosedeKruif** [comment]
Elastic Search query string query notes:
Reserved characters
If you need to use any of the characters which function as operators in your query itself (and not as operators), then you should escape them with a leading backslash. For instance, to search for (1+1)=2, you would need to write your query as \(1\+1\)\=2.
The reserved characters are: + - = && || > < ! ( ) { } [ ] ^ " ~ * ? : \ /
Failing to escape these special characters correctly could lead to a syntax error which prevents your query from running.

Watch this space

A space may also be a reserved character. For instance, if you have a synonym list which converts "wi fi" to "wifi", a query_string search for "wi fi" would fail. The query string parser would interpret your query as a search for "wi OR fi", while the token stored in your index is actually "wifi". Escaping the space will protect it from being touched by the query string parser: "wi\ fi".

However, if I try escaping the space or escaping the "-" I still get the same number of hits for the Coca Cola query.
Interesting...

dr  José de Kruif, Utrecht University, Digital Humanities Lab<http://digitalhumanities.wp.hum.uu.nl/>
Muntstraat 2a  T2.13A (KNG 20), 3512 EV Utrecht
Tel +31302537867
________________________________
Van: Melvin Wevers [notifications@github.com]
Verzonden: maandag 19 oktober 2015 11:08
Aan: UUDigitalHumanitieslab/texcavator
Onderwerp: [texcavator] Dash problems (#78)


When I do the search "Coca-Cola" it gives the same amount of results as when I enter "Coca Cola"
Texcavator interprets the - as a space. Is there a way I can circumvent this?

**Comment by melvinwevers** [comment]
Yes exactly. Escaping the character does not seem to work within quotation marks.

**Comment by mhkuu** [comment]
During indexation (in particular the tokenization phase) all hyphens of string fields (such as article title or text content) will get deleted, so essentially you're searching for the same thing, whether you escape the hyphens in the search query or not. 

See https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-analyzer.html, https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-tokenizer.html and then http://unicode.org/reports/tr29/ for full details.

If you want to circumvent this, you could export the results and do a text search with an external program. Or we can do a reindexing in which we add a field with the bare original content of the text content and allow the user to search on that instead of the analyzed text content.

**Comment by JosedeKruif** [comment]
Melvin, ben jij grote queries aan het doen? Ik kan niks meer......Ben ook bezig voor een artikel.

dr  José de Kruif, Utrecht University, Digital Humanities Lab<http://digitalhumanities.wp.hum.uu.nl/>
Muntstraat 2a  T2.13A (KNG 20), 3512 EV Utrecht
Tel +31302537867
________________________________
Van: Melvin Wevers [notifications@github.com]
Verzonden: maandag 19 oktober 2015 12:43
Aan: UUDigitalHumanitieslab/texcavator
CC: Kruif, J. de (José)
Onderwerp: Re: [texcavator] Dash problems (#78)


Yes exactly. Escaping the character does not seem to work within quotation marks.

**Comment by melvinwevers** [comment]
Nope. Aan het schrijven. Vanochtend wat kleine queries gedraaid.

**Comment by melvinwevers** [comment]
Back on topic: I think exporting does not solve the problem. 

For instance, if I query "Coca-Cola" NOT "Cola", I find no article because of this problem. 

I think you can best decide how to solve this problem.

**Comment by mhkuu** [comment]
Let's discuss this this afternoon! :-)

**Comment by melvinwevers** [comment]
I just tried this query: "land van de gangster". If I'm correct, this should look for this particular string, however, it finds an article with the following sentence: "Zeer trots op deze dienst aan het hoogste uitvoerende gezag van zün land heeft de gangster zijn „dienst" overal rondgebazuind"

Could this be that stop-words are filtered out during indexation/tokenization?

**Comment by jgonggrijp** [comment]
@melvinwevers This is a new issue. Please create new tickets for new issues, like I have done now (see reference directly above this message).

**Comment by melvinwevers** [comment]
I will do create new issues in the future. I figured this one was related.

**Comment by jgonggrijp** [comment]
It is impossible to distinguish spellings with or without `-` because of technical restrictions in ElasticSearch. The solution is to search for "coca cola", download the set and continue your analysis offline.
