### ISSUE TITLE
Word-in-context information

### ISSUE THREAD

**Issue by jgonggrijp** [UUDigitalHumanitieslab/texcavator#79]
Taken from @melvinwevers in [#74](https://github.com/UUDigitalHumanitieslab/texcavator/issues/74#issuecomment-149477796):

> However, I would also like an additional feature (maybe this is another issue, but it is related) that would allow me to search for words within a query. And more importantly to have information on this word. I could see for instance how often Amerika (relative frequency) within a corpus based on the query: "Vietnam AND Soviet" 
> Now I can of course add Amerika to query, but I only see the absolute number of articles increasing. I cannot see the relative frequency of the words (relative to the amount of words/tokens in the corpus). This would be more telling, I think.

**Comment by jgonggrijp** [comment]
If you count the number of hits that results from the query

> +Vietnam +Soviet

and compare it to the number of hits for

> +Vietnam +Soviet +Amerika

(which should be smaller),

would that answer your question?

**Comment by melvinwevers** [comment]
No. Since I'm not interested the amount of articles, but words.

**Comment by mhkuu** [comment]
But you can get the number of times "Amerika" appears in the query "+Vietnam +Soviet" from the word cloud counts, right?

**Comment by melvinwevers** [comment]
If it appears in the word cloud that is.

**Comment by mhkuu** [comment]
Agreed, but if it's the same information as in the word cloud, we should be able to retrieve that somehow :-) Thanks for the clarification.

**Comment by mhkuu** [comment]
I think we concluded this is related to #82.
