### ISSUE TITLE
Number of words in word cloud not modifiable

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#80]
There is an option in the configuration where you can set the number of words in the word cloud. But in the code, this number is hardcoded to 100. If we recreate this feature, we do want to set a max (200) and min (1).

**Comment by melvinwevers** [comment]
Why a minimum value? 

This option used to work > that is you could set the number of words in the word cloud.

**Comment by mhkuu** [comment]
Found out that it actually is modifiable, but only to a lower value than 100: on the back end only the first 100 results are returned, on the front end the number of words is limited by the parameter setting. So while this is still a bug (you can never get more than 100 words), it's less blocking than I thought.

**Comment by mhkuu** [comment]
This was actually fixed during #69, you can select between 1 and 200 words.
