### ISSUE TITLE
Re-search, using a query as a corpus

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#82]
The idea is that you are able to search within a saved query. 

Probably best if we create a mock-up of this before actually coding it out.

**Comment by mhkuu** [comment]
I'm really struggling with this issue. 

Returning total word frequencies for a single term not appearing in the word cloud, given a search query, as was the original use case (see #79), is doable (by making the whole set (and not only the first 100) of frequency counts downloadable for example).

Enabling one to search (and filter) on a subquery is going to be a hell of a job to implement (>100 hours) and I'm reluctant to spent that much time on a feature without being sure that it's really going to improve the user experience.

**Comment by melvinwevers** [comment]
That makes sense. Let's discuss next week, whether we should continue with this feature.
