### ISSUE TITLE
Timelines: y-axis on normalization unclear (?)

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#86]
From @melvinwevers at #71:

> Moreover, it is not clear how to interpret the y-axis for the normalized timeline. These are no longer absolute numbers. 

> This issue has high priority (for me) since I would like to implement screenshots of timelines in my dissertation. I can now only use the absolute timelines, it would be great to also have the normalized ones. 

> Which makes me wonder. Should we divide the frequency by the total number of documents in the newspaper archive, or by the total number of articles within the specific corpus we are investigation (based on our meta-data this could be Dutch/National/Article. 

Questions/comments from me: 

- Did you mean to reopen #71? Is there still something broken? 
- What do you mean with "these are no longer absolute numbers?" Can you attach a screenshot? 
- We are open to any suggestion for normalizing; but let's start with fixing any existing bugs.

**Comment by melvinwevers** [comment]
If I recall correctly we discussed different ways of normalizing the timeline. 
I think we discussed that it now takes the peak and normalizing everything according to this peak. 
Another option would be to normalize by dividing every year with the number of documents in this year. If we would do this we would run into the problem of what the total number of documents would be—everything, only the national newspapers. In other words, should this be dependent on your meta-data filtering. 

Regarding the absolute numbers. When you turn on normalization, the y-axis displays a number and I'm not sure what this means. Also when you hover over a bar, it gives a number. In this case the peak displays 431.5 documents. However, after clicking on it you get 121 documents. This is a bit unclear. 

<img width="788" alt="screenshot 2015-11-12 10 08 33" src="https://cloud.githubusercontent.com/assets/6586849/11114604/31a29726-8926-11e5-9d0d-64a14b91610f.png">

**Comment by mhkuu** [comment]
The number on hover shows the normalized count (so # documents divided by peak # documents in the selected period). If you click on a bar, in both the normalized as absolute variant, the documents for that year are shown.

I'll create a new issue to reflect your thoughts in the comment.
