### ISSUE TITLE
Change data export

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#9]
* Filename: query name + date executed
* Metadata of query on first line of results. 
  * @mhkuu: does KB have a version numbering for the corpus? Would be nice to include that!

**Comment by mhkuu** [comment]
Metadata: 
- query comment
- exact query
- date executed
- filter settings (i.e. distribution, article type, date window)

**Comment by mhkuu** [comment]
I'll keep the username in the filename; we could otherwise get conflicting filenames.

**Comment by melvinwevers** [comment]
@mhkuu Do you have an example of how the title of the file and the first line would look?

**Comment by mhkuu** [comment]
Yes, I just downloaded a search named "oxford" (with a very insightful comment) locally: 

Filename: `tex_oxford_2015.04.17-15.14.22.zip`
First two lines of resulting .csv-file: 

| comment | query | date executed | excluded article types | excluded distributions | date lower | date upper |
| ------- | ----- | ------------- | ---------------------- | ---------------------- | ---------- | ---------- |
| sdfdsfdsfdsfs | oxford | 2015-04-17 15:14:22.999000 | [u'st_advert'] | [u'sd_antilles'] | 1878-01-01 | 1936-05-29 |

I'll look into the formatting of the date executed and the excluded article types/distributions.

**Comment by melvinwevers** [comment]
Would it be an idea to add the meta-information at the bottom or in a column instead of a row? 
Many programmes expect the first row to contain row information. I now need to first remove this first row to be able to do anything with the files.

**Comment by mhkuu** [comment]
Good idea, I moved comment to a new issue: #66.
