### ISSUE TITLE
No word clouds

### ISSUE THREAD

**Issue by JosedeKruif** [UUDigitalHumanitieslab/texcavator#91]
When asking for a word cloud, Texcavator often refuses. Restarting (putty) helps. However, it would be nice if restarting was not necessary. Apache seems not to be the problem, Texcavator starts allright, just refuses to generate clouds. Celery seems not to be the problem, because restarting helps. ??

**Comment by jgonggrijp** [comment]
What exactly does Texcavator do when it refuses to generate your word cloud, in this particular case? What do you (not) see on your screen? Does it show a popup saying "Request failed"? Does the word cloud tab open to the foreground? Does the progress bar appear? Do you ever get a "Cloud data request failed" error message?

**Comment by jgonggrijp** [comment]
Answer: "Request failed".

**Comment by jgonggrijp** [comment]
I have inserted additional logging statements. Please drop me a note when the word cloud is refusing again.

**Comment by jgonggrijp** [comment]
Update: I will only monitor logs on the HPC and IM servers.

**Comment by mhkuu** [comment]
Closing this for the moment as cloud generation seems really stable since we've moved to the new server at SurfSara.
