### ISSUE TITLE
Remove duplicate issues (Telegraaf etc.) from KB index

### ISSUE THREAD

**Issue by jesperverhoef** [UUDigitalHumanitieslab/texcavator#94]
(In Dutch, for I have a Christmas lunch to attend in half an hour.)

Een groot probleem waar ik gisteren bij toeval tegenaan liep: we wisten al dat er in Tex veel minder krantennummers zitten dan in Delpher (en verrassend genoeg in sommige opzichten meer: ik kom bijv. Parools tegen in Tex en ook een keer Volkskranten - dit is een ander punt, maar is inmiddels al bekend hoe dit kan?), maar wat De Telegraaf aangaat is dit verschil echt gigantisch. Liep hier tegenaan toen ik mijn quiz-bestand van de jaren vijftig in OpenRefine laadde, en me opviel dat er niet één Telegraaf-artikel tussen zat. Terwijl als ik dezelfde query in Delpher invoer er meer dan achthonderd resultaten komen. 

Heb dit even nagezocht door in zowel Tex (met de volgende, simpele query: +man +paper_dc_title: "De Telegraaf") als Delpher (via dat uitklapmenuutje, daar instellingen goed gezet) te zoeken op het woord 'man', alleen artikelen, en dat dan per decennium, alleen in De Telegraaf. Ik vond de verschillen zeer groot, geef ze hier even weer, eerst Tex, dan Delpher:
1950s 2439 vs. 54.510
1960s 37.542 vs. 101.878
1970s 68.069 vs. 134.578
1980s 62.836 vs. 119.977

Ik weet: in Delpher zitten die dubbele Telegrafen nog, zij kunnen de verschillen wat betreft de jaren zeventig en tachtig waarschijnlijk goed verklaren. Maar dit geldt niet voor de jaren vijftig en zestig. Dit verschil komt ook terug in andere queries (bijv. hond: resp. 148 en 2246 in Tex en Delpher in 1950s; 1599 resp. 4288 in 1960s). 

Heb reeds wat gecorrespondeerd met Melvin en Pim, we vermoeden dat e.e.a. te maken heeft met het feit dat we alle Telegrafen met een bepaalde ID uit Tex gehaald hebben. (Het zou bijvoorbeeld kunnen dat de KB de jaren 52-1960 heeft ingescand en toen ook de jaren 70 met eenzelfde ID.) Waarschijnlijk heeft het verwijderen uit Tex van Telegrafen met bepaalde ID's, onbedoeld en ongelukkigerwijs, tot gevolg gehad dat er vele Telegrafen ontbreken in de jaren vijftig en - maar dit is minder duidelijk, daar de verschillen hier minder groot zijn - de jaren zestig. 

Het behoeft denk ik amper toelichting dat dit een zeer urgent probleem is: het belet analyses op data uit de jaren vijftig en zestig, en maakt dat analyses die ik de afgelopen weken gedaan heb opnieuw zal moeten doen. De oplossing ligt, als gezegd, vermoedelijk in de ID's: misschien kan geïmplementeerd worden dat alleen de dubbele eruit gefilterd worden voor de periode waarin deze voorkwamen in de KB, dus 1970 t/m 1987? Dit is natuurlijk een schot voor de boeg, het is raadzaam eerst precies uit te zoeken wat het probleem precies veroorzaakt. Hopelijk kan dit dan z.s.m. verholpen worden: dit heeft voor de onderzoekers absolute prioriteit.

**Comment by jesperverhoef** [comment]
Een zgn. hotfix is misschien nu het handigst, dus het filter weghalen bij de query. Dit zou betekenen dat gebruikers (voorlopige) zelf afhankelijk van periode dat ID eruit filteren. Het ID filteren in Tex by default voor de periode 1970 t/m 1987 zou dan later geïmplementeerd kunnen worden.

**Comment by mhkuu** [comment]
Hoi @jesperverhoef, 

Dat is vervelend. Ik heb zojuist inderdaad een hotfix uitgevoerd op de productie- en ontwikkelomgeving; het filter wordt niet meer standaard toegevoegd. Je kunt nog wel handmatig filteren doen door `-identifier:ddd\:11*` aan je zoekquery toe te voegen. 

Ik stel voor dat iemand binnen het project de leiding neemt om deze dubbelingen samen met de KB zo snel mogelijk uit de wereld te helpen. 

Groeten, Martijn.

**Comment by JosedeKruif** [comment]
Beste allen,

Martijn, heel hartelijk dank voor deze kerst hotfix.

Wat betreft de set: Hierover is al minstens anderhalf jaar overleg gaande met Steven Claeyssens van de KB, Jeroen Schot en zijn collega's van Surf Sara en onder andere ondergetekende. Alle collega's die met de KBkranten werken hebben hier behoorlijke hinder van, dus ook andere onderzoeksgroepen balen.  Steven zit er achteraan, weet ik, maar bereikt ook niet veel.
Ik ben ook benieuwd of Pim dit tijdens zijn stationering bij de KB nog aan de orde heeft gesteld?
In ieder geval ben ik hier behoorlijk klaar mee. Ik wil na de kerstvakantie flink druk gaan uitoefenen en zal Joris vragen om zich er nu ook achter te gaan zetten.
Ik overweeg een overleg op te starten,  waarbij bijvoorbeeld Huub Wijfjes ook wordt uitgenodigd, die wordt nu fellow bij de KB. Dan kunnen we namens de gezamenlijke onderzoekers een brandbrief maken, waarbij we verzoeken de set nu ein-de-lijk op te schonen.

Allemaal een plezierige kerst gewenst,

José de Kruif

Op 25 dec. 2015 om 15:07 heeft Martijn <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hoi @jesperverhoef<https://github.com/jesperverhoef>,

Dat is vervelend. Ik heb zojuist inderdaad een hotfix uitgevoerd op de productie- en ontwikkelomgeving; het filter wordt niet meer standaard toegevoegd. Je kunt nog wel handmatig filteren doen door -identifier:ddd\:11* aan je zoekquery toe te voegen.

Ik stel voor dat iemand binnen het project de leiding neemt om deze dubbelingen samen met de KB zo snel mogelijk uit de wereld te helpen.

Groeten, Martijn.

**Comment by melvinwevers** [comment]
Ik ben tussen de kerstkransjes en de oliebollen in even door het archief geplozen. 
Het filter dient gebruik te worden voor de volgende periodes:

1951
07 t/m 12-1962
01 t/m 09 -1963
7-1965
10-1965
04-1966 t/m 11-1966
1969
1970-1989

Ik heb dit uitgevonden door de aantallen Telegrafen te vergelijken per jaar (met en zonder filter). Soms bleek dat het filter niet de helft weghaalde maar meer. Toen ben ik per maand gaan kijken wat het effect van het filter was. Zie de cijfers hier: https://docs.google.com/spreadsheets/d/1c21xAXokusice9DQWg4jT_OCJvOB07qNcGM9V2Q6RgI/edit?usp=sharing

@JosedeKruif goed dat er druk wordt gezet. Want dit is erg hinderlijk en het staat degelijke analyses in de weg. 

@jesperverhoef: zou jij dit nog eens kunnen dubbel-checken. 

@mhkuu is het mogelijk om het filter specifiek toe te voegen aan bepaalde query? Of anders deze dubbelingen uit het archief te halen. 
Het is namelijk heel tijdrovend voor ons om voor elke query het filter per jaar of maand toe te voegen.

**Comment by mhkuu** [comment]
(switching back to English) 

Thanks for your analysis @melvinwevers! We will try to see whether there's a good way to filter out these issues of De Telegraaf, other than by date; maybe there's something in the metadata we can use. 

@PimHuijnen just showed us the graph on kranten.delpher.nl, which, if you filter for De Telegraaf, shows that the amounts go awry after 1949 (when the newspaper only had a single edition, while before WWII it had a day and evening edition). You would expect an even line after 1949, but instead there's spikes all over the place.

Interestingly, there's no spike in 1951 while you list that as a possible period with duplicates, we will have to investigate that.

**Comment by melvinwevers** [comment]
@mhkuu this analysis is a bit out-dated by now. I discovered that there are also other newspapers with the ID 11 that are duplicates, but not all the time (as with the De Telegraaf), and sometimes only for particular months within a year. 

Using the ID + specific keywords I have established when and which newspapers are double. > this analysis is not perfect but it at least filters out a great deal of the newspapers. But with access to the entire datasets there is probably a better way of filtering them out. If I can help you out with the duplicates let me know.

**Comment by melvinwevers** [comment]
With regards to your question about 1951. The second half of 1951 all have the ID11 without duplicates, and the first half has other id's. So filtering for ID11 leaves only the first half of the year, thus no filter for 1951. The google drive spreadsheet is updated btw, but it includes all my notes and might not be legible for non-Melvins.

**Comment by JosedeKruif** [comment]
Intensief overleg geweest met KB en Surf Sara. De KB bezweert mij dat er eerdaags een nieuwe ontdubbelde set komt. Helaas weigeren ze een termijn te noemen ;(. Ik heb ze ervan op de hoogte gesteld dat er publicaties beginnen te verschijnen op basis van hun niet-integere set en dat b: lang niet elk onderzoeksproject (b.v. dat van Huub Wijfjes) op de hoogte is van het feit dat er zoveel dubbelen in de set zitten. Zodat de bal nadrukkelijk bij de KB ligt.
