### ISSUE TITLE
MySQL VARCHAR column collation for unique index

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#95]
MySQL can't have an unique index on VARCHAR columns if the collation is the default utf-8, as this will e.g. think that "ideeën" and "ideeen" are equal (which might be true in this case, but probably not in all cases). Therefore, this query needs to be applied after migration 0013 of the query app: 

```
alter table query_term modify word varchar(200) character set utf8 collate utf8_bin;
```

I haven't yet found a way to apply this automagically, maybe this is something for the puppet script.

**Comment by jgonggrijp** [comment]
What is the current state (temporary fix)?

**Comment by jgonggrijp** [comment]
Answer: did it manually.

**Comment by jgonggrijp** [comment]
@mhkuu I can probably implement this as a custom migration operation. However, it will be inserted after 0017 instead of after 0013. Is that acceptable?

Note to self: the collation before the alteration is `utf8_general_ci`.

**Comment by mhkuu** [comment]
@jgonggrijp That would be great! We might want to say something about this in the documentation.

**Comment by jgonggrijp** [comment]
Update: I'm going to insert it after 0016. This is cleaner because it allows me to merge the fix independently of `feature/timeline-normalization`. We will have two migrations numbered 1700, but Django has solutions for that.
